use_frameworks!


target 'Transloadit_MacOS_Example' do
  pod 'TransloaditKit', :path => '../'
end


target 'Transloadit_Example' do
  pod 'TransloaditKit', :path => '../'
  target 'Transloadit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
