use_frameworks!


target 'Transloadit_MacOS_Example' do
  pod 'TransloaditKit', :path => '../'
end


target 'Transloadit_Example' do
  pod 'TransloaditKit', :path => '../'
pod 'Arcane', git: 'https://github.com/onmyway133/Arcane'
  target 'Transloadit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
